import { GetServerSideProps, NextPage } from "next";
import { Head } from "next/document";
import Link from "next/link";
import client from "../apollo/client";
import Image from "next/image";
import { ApolloRes, IPools } from "../apollo/interfaces";
import { Pools } from "../apollo/quieries";

const PoolsListPage: NextPage<IPools & ApolloRes> = ({
  pools,
  loading,
  error,
}) => {
  console.log(pools);
  if (loading) {
    return <p>loading</p>;
  }
  if (error) {
    return <p>error</p>;
  }

  const poolsArray = pools.filter((item) => item.token1.name !== "NFT");
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
      <h1>CD working</h1>
      {poolsArray.map((item, key) => {
        const token = item.id;
        const name = item.token0.symbol + "_" + item.token1.symbol;

        return (
          <div>
            <Link href={`pools/${item.id}`}>
              <h1>{name}</h1>
            </Link>
          </div>
        );
      })}
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const { data, error, loading } = await client.query<IPools>({
    query: Pools,
  });

  return {
    props: {
      pools: data.pools,
      error: !!error,
      loading,
    },
  };
};

export default PoolsListPage;
